import pygame

WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 1000

BOARD_SIZE = 800

MARGIN = 20
GAP = 20

PLAYER_PANEL_HEIGHT = 80
SIDEBAR_WIDTH = 340


BOARD_X = MARGIN
BOARD_Y = MARGIN + PLAYER_PANEL_HEIGHT

SIDEBAR_X = BOARD_X + BOARD_SIZE + GAP
SIDEBAR_Y = MARGIN
SIDEBAR_HEIGHT = WINDOW_HEIGHT - (MARGIN * 2)


PLAYER_TOP_RECT = pygame.Rect(
    BOARD_X,
    MARGIN,
    BOARD_SIZE,
    PLAYER_PANEL_HEIGHT,
)

BOARD_RECT = pygame.Rect(
    BOARD_X,
    BOARD_Y,
    BOARD_SIZE,
    BOARD_SIZE,
)

PLAYER_BOTTOM_RECT = pygame.Rect(
    BOARD_X,
    BOARD_Y + BOARD_SIZE,
    BOARD_SIZE,
    PLAYER_PANEL_HEIGHT,
)

SIDEBAR_RECT = pygame.Rect(
    SIDEBAR_X,
    SIDEBAR_Y,
    SIDEBAR_WIDTH,
    SIDEBAR_HEIGHT,
)
